apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers-cr
rules:
  # Core API resources in all namespaces
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - persistentvolumeclaims
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Deployments, StatefulSets, ReplicaSets
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Jobs and CronJobs
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Autoscaling
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # View namespaces (read-only)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-binding
subjects:
  - kind: Group
    name: developers
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: developers-cr
  apiGroup: rbac.authorization.k8s.io
