apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nodeapi-canary
  namespace: nodejs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
        - name: nodeapi
          image: nginx:1.28 # Replace with your image
          ports:
            - containerPort: 3000
  strategy:
    canary:
      canaryService: nodeapi-canary-service
      stableService: nodeapi-stable-service
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 100
        - pause: {}
