apiVersion: v1
kind: Service
metadata:
  name: nodeapi-stable-service
  namespace: nodejs-api
spec:
  selector:
    app: nodeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi-canary-service
  namespace: nodejs-api
spec:
  selector:
    app: nodeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
