apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-app-secrets
  namespace: my-app-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-app-database-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"
  secretObjects:
    - secretName: my-app-db-secret
      type: Opaque
      data:
        - objectName: "db_username"
          key: username
        - objectName: "db_password"
          key: password
