---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
  namespace: nodejs-api
spec:
  selector:
    app: nodejs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
