---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: nginx:1.21
          ports:
            - containerPort: 80
          env:
            - name: Database_URL
              value: "postgresql://user:password@localhost:5432/mydb"
          livenessProbe:
            httpGet:
              path: / # health doesn't exist
              port: 80 # instead of 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: / #/ready doesn't exist
              port: 80 # instead of 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: web-app-service
spec:
  type: ClusterIP
  selector:
    app: web-app # wrong value 'web'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
